import { isIP } from "node:net";
import type { AgentEvent, ExecutionPolicy, ToolDefinition } from "@forge/protocol";

export type Message = { role: "system"|"user"|"assistant"|"tool"; content: string; toolCallId?: string; toolCalls?: ToolCall[] };
export type ToolCall = { id: string; name: string; arguments: unknown };
export type ModelTurn = { content: string; toolCalls: ToolCall[]; usage: { inputTokens: number; outputTokens: number } };
export type ProviderConfig = { kind: "openai"|"anthropic"|"openai-compatible"; baseUrl: string; model: string; apiKey: string };
export interface CompletionProvider { complete(messages: Message[], tools: ToolDefinition<any>[], signal: AbortSignal): Promise<ModelTurn>; dispose?():void; }
export type ModelTransport = (input:{path:string;headers:Record<string,string>;body:unknown;signal:AbortSignal})=>Promise<unknown>;

const privateV4=(ip:string)=>/^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(ip);
export function validateModelEndpoint(value:string,allowPrivate=false){const url=new URL(value);if(!["https:","http:"].includes(url.protocol)||url.username||url.password)throw new Error("invalid_model_endpoint");if(url.protocol==="http:"&&!allowPrivate)throw new Error("insecure_model_endpoint");if(isIP(url.hostname)&&(privateV4(url.hostname)||url.hostname==="::1")&&!allowPrivate)throw new Error("private_model_endpoint_requires_confirmation");return url}
export class HttpModelProvider implements CompletionProvider {
  constructor(private readonly config:ProviderConfig,private readonly allowPrivateEndpoint:boolean,private readonly transport:ModelTransport){validateModelEndpoint(config.baseUrl,allowPrivateEndpoint)}
  private async request(path:string,headers:Record<string,string>,body:unknown,signal:AbortSignal){return this.transport({path,headers,body,signal})}
  async complete(messages:Message[],tools:ToolDefinition<any>[],signal:AbortSignal):Promise<ModelTurn>{return validateTurn(await (this.config.kind==="anthropic"?this.anthropic(messages,tools,signal):this.openai(messages,tools,signal)))}
  private async openai(messages:Message[],tools:ToolDefinition<any>[],signal:AbortSignal){const data:any=await this.request("chat/completions",{authorization:`Bearer ${this.config.apiKey}`},{model:this.config.model,messages:messages.map(m=>m.role==="tool"?{role:"tool",content:m.content,tool_call_id:m.toolCallId}:{role:m.role,content:m.content,...(m.toolCalls?.length?{tool_calls:m.toolCalls.map(c=>({id:c.id,type:"function",function:{name:c.name,arguments:JSON.stringify(c.arguments)}}))}:{})}),tools:tools.map(t=>({type:"function",function:{name:t.name,description:`Risk: ${t.risk}`,parameters:jsonSchema(t.schema)}})),tool_choice:"auto",parallel_tool_calls:false},signal);const msg=data.choices?.[0]?.message;if(!msg)throw new Error("invalid_model_response");return {content:String(msg.content??""),toolCalls:(msg.tool_calls??[]).map((c:any)=>({id:String(c.id),name:String(c.function?.name),arguments:parseArguments(c.function?.arguments)})),usage:{inputTokens:Number(data.usage?.prompt_tokens??0),outputTokens:Number(data.usage?.completion_tokens??0)}}}
  private async anthropic(messages:Message[],tools:ToolDefinition<any>[],signal:AbortSignal){const system=messages.filter(m=>m.role==="system").map(m=>m.content).join("\n");const converted=messages.filter(m=>m.role!=="system").map(m=>m.role==="tool"?{role:"user",content:[{type:"tool_result",tool_use_id:m.toolCallId,content:m.content}]}:{role:m.role,content:[{type:"text",text:m.content},...(m.toolCalls??[]).map(c=>({type:"tool_use",id:c.id,name:c.name,input:c.arguments}))]});const data:any=await this.request("messages",{"x-api-key":this.config.apiKey,"anthropic-version":"2023-06-01"},{model:this.config.model,max_tokens:4096,system,messages:converted,tools:tools.map(t=>({name:t.name,description:`Risk: ${t.risk}`,input_schema:jsonSchema(t.schema)}))},signal);return {content:(data.content??[]).filter((x:any)=>x.type==="text").map((x:any)=>x.text).join(""),toolCalls:(data.content??[]).filter((x:any)=>x.type==="tool_use").map((x:any)=>({id:String(x.id),name:String(x.name),arguments:x.input})),usage:{inputTokens:Number(data.usage?.input_tokens??0),outputTokens:Number(data.usage?.output_tokens??0)}}}
  dispose(){this.config.apiKey=""}
}
function parseArguments(value:unknown){if(typeof value!=="string")return {};if(Buffer.byteLength(value)>256*1024)throw new Error("tool_arguments_too_large");try{return JSON.parse(value)}catch{throw new Error("invalid_tool_arguments")}}
function validateTurn(turn:ModelTurn){if(typeof turn.content!=="string"||Buffer.byteLength(turn.content)>1024*1024||!Array.isArray(turn.toolCalls)||turn.toolCalls.length>1)throw new Error("invalid_model_response");for(const call of turn.toolCalls){if(!/^[A-Za-z0-9_-]{1,200}$/.test(call.id)||!/^[A-Za-z0-9_-]{1,100}$/.test(call.name))throw new Error("invalid_model_response");let encoded:string;try{encoded=JSON.stringify(call.arguments??null)}catch{throw new Error("invalid_tool_arguments")}if(Buffer.byteLength(encoded)>256*1024)throw new Error("tool_arguments_too_large")}for(const value of [turn.usage.inputTokens,turn.usage.outputTokens])if(!Number.isSafeInteger(value)||value<0||value>100_000_000)throw new Error("invalid_model_usage");return turn}
function jsonSchema(schema:any){return schema?._def?.typeName==="ZodObject"?{type:"object",properties:Object.fromEntries(Object.entries(schema.shape).map(([key,value]:any)=>[key,zodProperty(value)])),required:Object.entries(schema.shape).filter(([,v]:any)=>!v.isOptional()).map(([k])=>k),additionalProperties:false}:{type:"object",additionalProperties:false}}
function zodProperty(value:any):any{const type=value?._def?.typeName;return type==="ZodString"?{type:"string"}:type==="ZodNumber"?{type:"number"}:type==="ZodBoolean"?{type:"boolean"}:type==="ZodArray"?{type:"array",items:zodProperty(value._def.type)}:type==="ZodEnum"?{type:"string",enum:value._def.values}:type==="ZodLiteral"?{const:value._def.value}:type==="ZodOptional"||type==="ZodDefault"?zodProperty(value._def.innerType):type==="ZodEffects"?zodProperty(value._def.schema):{}}

type Task={id:string;deviceId:string;messages:Message[];provider:CompletionProvider;tools:Map<string,ToolDefinition<any>>;policy:ExecutionPolicy;controller:AbortController;events:AgentEvent[];sequence:number;turn:number;maxTurns:number;maxTokens:number;usedTokens:number;toolCallIds:Set<string>;pending?:ToolCall;status:"running"|"waiting"|"completed"|"failed"|"cancelled"};
export class AgentRuntime {
  private tasks=new Map<string,Task>();
  create(input:{taskId:string;deviceId:string;prompt:string;system:string;provider:CompletionProvider;tools:ToolDefinition<any>[];policy:ExecutionPolicy;maxTurns?:number;maxTokens?:number}){if(this.tasks.has(input.taskId))throw new Error("task_exists");if(Buffer.byteLength(input.prompt)>100_000||Buffer.byteLength(input.system)>100_000)throw new Error("prompt_too_large");const task:Task={id:input.taskId,deviceId:input.deviceId,messages:[{role:"system",content:input.system},{role:"user",content:input.prompt}],provider:input.provider,tools:new Map(input.tools.map(t=>[t.name,t])),policy:input.policy,controller:new AbortController(),events:[],sequence:0,turn:0,maxTurns:Math.min(input.maxTurns??20,50),maxTokens:Math.min(input.maxTokens??200000,1000000),usedTokens:0,toolCallIds:new Set(),status:"running"};this.tasks.set(task.id,task);this.event(task,"task.status",{status:"running"});void this.advance(task);return this.snapshot(task.id)}
  events(id:string,after=-1){return this.get(id).events.filter(e=>e.sequence>after)}
  snapshot(id:string){const t=this.get(id);return {id:t.id,status:t.status,pending:t.pending?publicToolCall(t.pending):undefined,turn:t.turn,usedTokens:t.usedTokens,maxTokens:t.maxTokens}}
  remove(id:string){const t=this.get(id);if(t.status==="running"||t.status==="waiting")throw new Error("task_active");t.messages.length=0;t.events.length=0;this.tasks.delete(id)}
  cancel(id:string){const t=this.get(id);if(t.status!=="running"&&t.status!=="waiting")return this.snapshot(id);t.controller.abort();t.status="cancelled";this.event(t,"task.status",{status:"cancelled"});this.finish(t);return this.snapshot(id)}
  cancelAll(){for(const id of this.tasks.keys())this.cancel(id)}
  async approve(id:string,toolCallId:string,approved:boolean){const t=this.get(id);if(t.status!=="waiting"||t.pending?.id!==toolCallId)throw new Error("approval_not_pending");const call=t.pending;t.pending=undefined;if(!approved){t.messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify({error:"user_denied"})});t.status="running";void this.advance(t);return this.snapshot(id)}await this.execute(t,call);t.status="running";void this.advance(t);return this.snapshot(id)}
  private async advance(t:Task){try{while(t.status==="running"&&t.turn++<t.maxTurns){if(messageBytes(t.messages)>8*1024*1024)throw new Error("context_budget_exceeded");const turn=validateTurn(await t.provider.complete(t.messages,[...t.tools.values()],t.controller.signal));t.usedTokens+=turn.usage.inputTokens+turn.usage.outputTokens;if(t.usedTokens>t.maxTokens)throw new Error("token_budget_exceeded");this.event(t,"message.delta",{content:turn.content,inputTokens:turn.usage.inputTokens,outputTokens:turn.usage.outputTokens,totalTokens:t.usedTokens});t.messages.push({role:"assistant",content:turn.content,toolCalls:turn.toolCalls});if(!turn.toolCalls.length){t.status="completed";this.event(t,"task.completed",{turns:t.turn,totalTokens:t.usedTokens});this.finish(t);return}for(const call of turn.toolCalls){if(t.toolCallIds.has(call.id))throw new Error("duplicate_tool_call_id");t.toolCallIds.add(call.id);const tool=t.tools.get(call.name);if(!tool){t.messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify({error:"unknown_tool"})});continue}const parsed=tool.schema.safeParse(call.arguments);if(!parsed.success){t.messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify({error:"invalid_arguments"})});continue}const decision=t.policy.evaluate({tool:tool.name,path:(parsed.data as any)?.path,command:(parsed.data as any)?.command});if(decision==="deny"){t.messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify({error:"policy_denied"})});continue}if(decision==="ask"){t.pending={...call,arguments:parsed.data};t.status="waiting";this.event(t,"approval.request",{toolCall:publicToolCall(t.pending),risk:tool.risk});return}await this.execute(t,{...call,arguments:parsed.data})}}if(t.status==="running")throw new Error("max_turns_exceeded")}catch(error:any){if(t.controller.signal.aborted)return;t.status="failed";this.event(t,"error",{code:safeError(error)});this.finish(t)}}
  private async execute(t:Task,call:ToolCall){const tool=t.tools.get(call.name)!;this.event(t,"tool.request",{id:call.id,name:call.name});try{const result=await tool.execute(call.arguments,t.controller.signal);const encoded=JSON.stringify(result??null);if(Buffer.byteLength(encoded)>3*1024*1024)throw new Error("tool_result_too_large");t.messages.push({role:"tool",toolCallId:call.id,content:encoded});if(tool.risk==="write"){const args=call.arguments as Record<string,unknown>;this.event(t,"file.changed",{tool:call.name,path:typeof args.path==="string"?args.path:"",destination:typeof args.destination==="string"?args.destination:""})}if(call.name==="run_command"&&result&&typeof result==="object"){const output=result as Record<string,unknown>;this.event(t,"terminal.output",{stdout:clipOutput(output.stdout),stderr:clipOutput(output.stderr),exitCode:typeof output.exitCode==="number"?output.exitCode:null,timedOut:output.timedOut===true})}this.event(t,"task.status",{status:"tool_completed",tool:call.name})}catch(error){t.messages.push({role:"tool",toolCallId:call.id,content:JSON.stringify({error:safeError(error)})})}}
  private event(t:Task,type:AgentEvent["type"],payload:Record<string,unknown>){t.events.push({taskId:t.id,deviceId:t.deviceId,sequence:t.sequence++,timestamp:new Date().toISOString(),type,payload});if(t.events.length>2000)t.events.splice(0,t.events.length-2000)}
  private finish(t:Task){t.provider.dispose?.();t.messages.length=0;t.pending=undefined}
  private get(id:string){const t=this.tasks.get(id);if(!t)throw new Error("task_not_found");return t}
}
function safeError(error:unknown){const code=error instanceof Error?error.message:"unknown_error";return /^[a-z0-9_]+$/i.test(code)?code:"operation_failed"}
function publicToolCall(call:ToolCall){const args=call.arguments&&typeof call.arguments==="object"?{...(call.arguments as Record<string,unknown>)}:{};if(typeof args.content==="string"){args.contentBytes=Buffer.byteLength(args.content);delete args.content}return {id:call.id,name:call.name,arguments:args}}
function messageBytes(messages:Message[]){let total=0;for(const message of messages){total+=Buffer.byteLength(message.content);if(message.toolCalls)for(const call of message.toolCalls)total+=Buffer.byteLength(JSON.stringify(publicToolCall(call)))}return total}
function clipOutput(value:unknown){if(typeof value!=="string")return "";const encoded=Buffer.from(value);return encoded.length<=200_000?value:`${encoded.subarray(0,200_000).toString("utf8")}\n[output truncated]`}
